### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by dwangaz-ust** [lululxvi/deep-learning-for-indentation#1]
I just downloaded all the data here and when I try to run the code, some errors occurred. 
![image](https://user-images.githubusercontent.com/66768978/84353026-f63e4c00-abf0-11ea-8b47-dcd2b696462b.png).
It seems like in the fit_n file, some data files cannot be found. And I still haven't understood which should be the peer file.

**Comment by lululxvi** [comment]
fit_n.py is just used to fit the strain-hardening exponent `n` shown in Fig. 5 and Fig. 9B. You need to get the values of sigma_y, sigma_0.008, sigma_0.015 and sigma_0.033 first, e.g., from the network prediction.
